name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
        
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name ${{ github.actor }}
       git config user.email razuyadav93@gmail.com
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.versionName }}
